sudo: required
language: node_js
node_js:
  - stable
#  - 6
#  - 5
#  - 4
#  - 0.12
#  - 0.11

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - npm run setup:config

script:
  - npm run test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
